// <auto-generated />
using System;
using Hemma.Modules.Economy.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hemma.Modules.Economy.Persistence.Migrations
{
    [DbContext(typeof(EconomyDbContext))]
    [Migration("20260604194008_AddEconomyCore")]
    partial class AddEconomyCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("economy")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("HouseholdId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_household_id_name");

                    b.ToTable("accounts", "economy");
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateOnly>("PeriodEndsOn")
                        .HasColumnType("date")
                        .HasColumnName("period_ends_on");

                    b.Property<DateOnly>("PeriodStartsOn")
                        .HasColumnType("date")
                        .HasColumnName("period_starts_on");

                    b.HasKey("Id")
                        .HasName("pk_budgets");

                    b.HasIndex("HouseholdId", "PeriodStartsOn")
                        .IsUnique()
                        .HasDatabaseName("ix_budgets_household_id_period_starts_on");

                    b.ToTable("budgets", "economy");
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.BudgetLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("Id")
                        .HasName("pk_budget_lines");

                    b.HasIndex("BudgetId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_lines_budget_id_category_id");

                    b.ToTable("budget_lines", "economy");
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Budgetable")
                        .HasColumnType("boolean")
                        .HasColumnName("budgetable");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_categories_household_id");

                    b.HasIndex("HouseholdId", "ParentCategoryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_household_id_parent_category_id_name");

                    b.ToTable("categories", "economy");
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.EconomySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<int>("CycleStartDay")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_start_day");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("default_currency");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.HasKey("Id")
                        .HasName("pk_economy_settings");

                    b.HasIndex("HouseholdId")
                        .IsUnique()
                        .HasDatabaseName("ix_economy_settings_household_id");

                    b.ToTable("economy_settings", "economy");
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.Account", b =>
                {
                    b.OwnsOne("Hemma.Modules.Economy.Domain.Money", "OpeningBalance", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("opening_balance_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("opening_balance_currency");

                            b1.HasKey("AccountId");

                            b1.ToTable("accounts", "economy");

                            b1.WithOwner()
                                .HasForeignKey("AccountId")
                                .HasConstraintName("fk_accounts_accounts_id");
                        });

                    b.Navigation("OpeningBalance")
                        .IsRequired();
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.BudgetLine", b =>
                {
                    b.HasOne("Hemma.Modules.Economy.Domain.Budget", null)
                        .WithMany("Lines")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_lines_budgets_budget_id");

                    b.OwnsOne("Hemma.Modules.Economy.Domain.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("BudgetLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("BudgetLineId");

                            b1.ToTable("budget_lines", "economy");

                            b1.WithOwner()
                                .HasForeignKey("BudgetLineId")
                                .HasConstraintName("fk_budget_lines_budget_lines_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.Budget", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
