// <auto-generated />
using System;
using Hemma.Modules.Economy.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hemma.Modules.Economy.Persistence.Migrations
{
    [DbContext(typeof(EconomyDbContext))]
    partial class EconomyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("economy")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("HouseholdId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_household_id_name");

                    b.ToTable("accounts", "economy");
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateOnly>("PeriodEndsOn")
                        .HasColumnType("date")
                        .HasColumnName("period_ends_on");

                    b.Property<DateOnly>("PeriodStartsOn")
                        .HasColumnType("date")
                        .HasColumnName("period_starts_on");

                    b.HasKey("Id")
                        .HasName("pk_budgets");

                    b.HasIndex("HouseholdId", "PeriodStartsOn")
                        .IsUnique()
                        .HasDatabaseName("ix_budgets_household_id_period_starts_on");

                    b.ToTable("budgets", "economy");
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.BudgetLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("Id")
                        .HasName("pk_budget_lines");

                    b.HasIndex("BudgetId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_lines_budget_id_category_id");

                    b.ToTable("budget_lines", "economy");
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Budgetable")
                        .HasColumnType("boolean")
                        .HasColumnName("budgetable");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_categories_household_id");

                    b.HasIndex("HouseholdId", "ParentCategoryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_household_id_parent_category_id_name");

                    b.ToTable("categories", "economy");
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.EconomySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<int>("CycleStartDay")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_start_day");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("default_currency");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.HasKey("Id")
                        .HasName("pk_economy_settings");

                    b.HasIndex("HouseholdId")
                        .IsUnique()
                        .HasDatabaseName("ix_economy_settings_household_id");

                    b.ToTable("economy_settings", "economy");
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.RecurringBill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("direction");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("NextDueOn")
                        .HasColumnType("date")
                        .HasColumnName("next_due_on");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_recurring_bills");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_recurring_bills_account_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_recurring_bills_category_id");

                    b.HasIndex("HouseholdId", "NextDueOn")
                        .HasDatabaseName("ix_recurring_bills_household_id_next_due_on");

                    b.ToTable("recurring_bills", "economy");
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.RecurringBillOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DueOn")
                        .HasColumnType("date")
                        .HasColumnName("due_on");

                    b.Property<Guid>("RecurringBillId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurring_bill_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_recurring_bill_occurrences");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_recurring_bill_occurrences_transaction_id");

                    b.HasIndex("RecurringBillId", "DueOn")
                        .IsUnique()
                        .HasDatabaseName("ix_recurring_bill_occurrences_recurring_bill_id_due_on");

                    b.ToTable("recurring_bill_occurrences", "economy");
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsPending")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pending");

                    b.Property<bool>("IsTransferOutflow")
                        .HasColumnType("boolean")
                        .HasColumnName("is_transfer_outflow");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date")
                        .HasColumnName("occurred_on");

                    b.Property<Guid?>("PayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("payer_id");

                    b.Property<string>("ReceiptBlobContainer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("receipt_blob_container");

                    b.Property<string>("ReceiptBlobKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("receipt_blob_key");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_id");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_transactions_account_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_transactions_category_id");

                    b.HasIndex("PayerId")
                        .HasDatabaseName("ix_transactions_payer_id");

                    b.HasIndex("TransferId")
                        .HasDatabaseName("ix_transactions_transfer_id");

                    b.HasIndex("HouseholdId", "OccurredOn")
                        .HasDatabaseName("ix_transactions_household_id_occurred_on");

                    b.ToTable("transactions", "economy");
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid>("InflowTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("inflow_transaction_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mode");

                    b.Property<Guid>("OutflowTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("outflow_transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_transfers");

                    b.HasIndex("InflowTransactionId")
                        .HasDatabaseName("ix_transfers_inflow_transaction_id");

                    b.HasIndex("OutflowTransactionId")
                        .HasDatabaseName("ix_transfers_outflow_transaction_id");

                    b.HasIndex("HouseholdId", "InflowTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_transfers_household_id_inflow_transaction_id");

                    b.HasIndex("HouseholdId", "OutflowTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_transfers_household_id_outflow_transaction_id");

                    b.ToTable("transfers", "economy");
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.Account", b =>
                {
                    b.OwnsOne("Hemma.Modules.Economy.Domain.Money", "OpeningBalance", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("opening_balance_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("opening_balance_currency");

                            b1.HasKey("AccountId");

                            b1.ToTable("accounts", "economy");

                            b1.WithOwner()
                                .HasForeignKey("AccountId")
                                .HasConstraintName("fk_accounts_accounts_id");
                        });

                    b.Navigation("OpeningBalance")
                        .IsRequired();
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.BudgetLine", b =>
                {
                    b.HasOne("Hemma.Modules.Economy.Domain.Budget", null)
                        .WithMany("Lines")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_lines_budgets_budget_id");

                    b.OwnsOne("Hemma.Modules.Economy.Domain.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("BudgetLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("BudgetLineId");

                            b1.ToTable("budget_lines", "economy");

                            b1.WithOwner()
                                .HasForeignKey("BudgetLineId")
                                .HasConstraintName("fk_budget_lines_budget_lines_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.RecurringBill", b =>
                {
                    b.HasOne("Hemma.Modules.Economy.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_bills_accounts_account_id");

                    b.HasOne("Hemma.Modules.Economy.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recurring_bills_categories_category_id");

                    b.OwnsOne("Hemma.Modules.Economy.Domain.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("RecurringBillId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("RecurringBillId");

                            b1.ToTable("recurring_bills", "economy");

                            b1.WithOwner()
                                .HasForeignKey("RecurringBillId")
                                .HasConstraintName("fk_recurring_bills_recurring_bills_id");
                        });

                    b.OwnsOne("Hemma.Modules.Economy.Domain.RecurringBillCadence", "Cadence", b1 =>
                        {
                            b1.Property<Guid>("RecurringBillId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("DayOfMonth")
                                .HasColumnType("integer")
                                .HasColumnName("cadence_day_of_month");

                            b1.Property<string>("Frequency")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("cadence_frequency");

                            b1.Property<int>("Interval")
                                .HasColumnType("integer")
                                .HasColumnName("cadence_interval");

                            b1.HasKey("RecurringBillId");

                            b1.ToTable("recurring_bills", "economy");

                            b1.WithOwner()
                                .HasForeignKey("RecurringBillId")
                                .HasConstraintName("fk_recurring_bills_recurring_bills_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Cadence")
                        .IsRequired();
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.RecurringBillOccurrence", b =>
                {
                    b.HasOne("Hemma.Modules.Economy.Domain.RecurringBill", null)
                        .WithMany("Occurrences")
                        .HasForeignKey("RecurringBillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_bill_occurrences_recurring_bills_recurring_bill_id");

                    b.HasOne("Hemma.Modules.Economy.Domain.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recurring_bill_occurrences_transactions_transaction_id");
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.Transaction", b =>
                {
                    b.HasOne("Hemma.Modules.Economy.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_accounts_account_id");

                    b.HasOne("Hemma.Modules.Economy.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_categories_category_id");

                    b.OwnsOne("Hemma.Modules.Economy.Domain.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("TransactionId");

                            b1.ToTable("transactions", "economy");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId")
                                .HasConstraintName("fk_transactions_transactions_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.Transfer", b =>
                {
                    b.HasOne("Hemma.Modules.Economy.Domain.Transaction", null)
                        .WithMany()
                        .HasForeignKey("InflowTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transfers_transactions_inflow_transaction_id");

                    b.HasOne("Hemma.Modules.Economy.Domain.Transaction", null)
                        .WithMany()
                        .HasForeignKey("OutflowTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transfers_transactions_outflow_transaction_id");
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.Budget", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Hemma.Modules.Economy.Domain.RecurringBill", b =>
                {
                    b.Navigation("Occurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
