// <auto-generated />
using System;
using Hemma.Modules.Property.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hemma.Modules.Property.Persistence.Migrations
{
    [DbContext(typeof(PropertyDbContext))]
    [Migration("20260611191502_AlignPropertyBlobKeyLengths")]
    partial class AlignPropertyBlobKeyLengths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("property")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hemma.Modules.Property.Domain.HistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("area");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid?>("SourceMaintenanceOccurrenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_maintenance_occurrence_id");

                    b.Property<Guid?>("SourceProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_project_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_history_entries");

                    b.HasIndex("HouseholdId", "Area")
                        .HasDatabaseName("ix_history_entries_household_id_area");

                    b.HasIndex("HouseholdId", "Date")
                        .HasDatabaseName("ix_history_entries_household_id_date");

                    b.HasIndex("HouseholdId", "Type")
                        .HasDatabaseName("ix_history_entries_household_id_type");

                    b.ToTable("history_entries", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.HistoryEntryPhoto", b =>
                {
                    b.Property<Guid>("HistoryEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("history_entry_id");

                    b.Property<string>("BlobKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("blob_key");

                    b.Property<string>("BlobContainer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("blob_container");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("HistoryEntryId", "BlobKey")
                        .HasName("pk_history_entry_photos");

                    b.ToTable("history_entry_photos", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.MaintenanceOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid?>("SpawnedProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("spawned_project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_occurrences");

                    b.HasIndex("PlanId", "DueDate")
                        .IsUnique()
                        .HasDatabaseName("ix_maintenance_occurrences_plan_id_due_date");

                    b.HasIndex("PlanId", "Status")
                        .HasDatabaseName("ix_maintenance_occurrences_plan_id_status");

                    b.HasIndex("HouseholdId", "Status", "DueDate")
                        .HasDatabaseName("ix_maintenance_occurrences_household_id_status_due_date");

                    b.ToTable("maintenance_occurrences", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.MaintenancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AnchorDate")
                        .HasColumnType("date")
                        .HasColumnName("anchor_date");

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("area");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("integer")
                        .HasColumnName("lead_time_days");

                    b.Property<int>("RecurrenceInterval")
                        .HasColumnType("integer")
                        .HasColumnName("recurrence_interval");

                    b.Property<string>("RecurrenceUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("recurrence_unit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_plans");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_maintenance_plans_household_id");

                    b.HasIndex("HouseholdId", "IsActive")
                        .HasDatabaseName("ix_maintenance_plans_household_id_is_active");

                    b.ToTable("maintenance_plans", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("area");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TargetEndDate")
                        .HasColumnType("date")
                        .HasColumnName("target_end_date");

                    b.Property<DateOnly?>("TargetStartDate")
                        .HasColumnType("date")
                        .HasColumnName("target_start_date");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_projects_household_id");

                    b.HasIndex("HouseholdId", "Area")
                        .HasDatabaseName("ix_projects_household_id_area");

                    b.HasIndex("HouseholdId", "Status")
                        .HasDatabaseName("ix_projects_household_id_status");

                    b.ToTable("projects", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.ProjectAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobContainer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("blob_container");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("blob_key");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_project_attachments");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_attachments_project_id");

                    b.ToTable("project_attachments", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.ProjectLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("label");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_project_links");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_links_project_id");

                    b.ToTable("project_links", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_project_tasks");

                    b.HasIndex("ProjectId", "SortOrder")
                        .HasDatabaseName("ix_project_tasks_project_id_sort_order");

                    b.ToTable("project_tasks", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.HistoryEntry", b =>
                {
                    b.OwnsOne("Hemma.Shared.Kernel.Domain.Money", "Cost", b1 =>
                        {
                            b1.Property<Guid>("HistoryEntryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("cost_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("cost_currency");

                            b1.HasKey("HistoryEntryId");

                            b1.ToTable("history_entries", "property");

                            b1.WithOwner()
                                .HasForeignKey("HistoryEntryId")
                                .HasConstraintName("fk_history_entries_history_entries_id");
                        });

                    b.Navigation("Cost");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.HistoryEntryPhoto", b =>
                {
                    b.HasOne("Hemma.Modules.Property.Domain.HistoryEntry", null)
                        .WithMany("Photos")
                        .HasForeignKey("HistoryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_history_entry_photos_history_entries_history_entry_id");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.Project", b =>
                {
                    b.OwnsOne("Hemma.Shared.Kernel.Domain.Money", "BudgetEstimate", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("budget_estimate_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("budget_estimate_currency");

                            b1.HasKey("ProjectId");

                            b1.ToTable("projects", "property");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId")
                                .HasConstraintName("fk_projects_projects_id");
                        });

                    b.Navigation("BudgetEstimate");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.ProjectAttachment", b =>
                {
                    b.HasOne("Hemma.Modules.Property.Domain.Project", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_attachments_projects_project_id");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.ProjectLink", b =>
                {
                    b.HasOne("Hemma.Modules.Property.Domain.Project", null)
                        .WithMany("Links")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_links_projects_project_id");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.ProjectTask", b =>
                {
                    b.HasOne("Hemma.Modules.Property.Domain.Project", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_tasks_projects_project_id");

                    b.OwnsOne("Hemma.Shared.Kernel.Domain.Money", "Estimate", b1 =>
                        {
                            b1.Property<Guid>("ProjectTaskId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("estimate_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("estimate_currency");

                            b1.HasKey("ProjectTaskId");

                            b1.ToTable("project_tasks", "property");

                            b1.WithOwner()
                                .HasForeignKey("ProjectTaskId")
                                .HasConstraintName("fk_project_tasks_project_tasks_id");
                        });

                    b.Navigation("Estimate");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.HistoryEntry", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.Project", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Links");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
