// <auto-generated />
using System;
using Hemma.Modules.Property.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hemma.Modules.Property.Persistence.Migrations
{
    [DbContext(typeof(PropertyDbContext))]
    partial class PropertyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("property")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hemma.Modules.Property.Domain.HistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid?>("SourceMaintenanceOccurrenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_maintenance_occurrence_id");

                    b.Property<Guid?>("SourceProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_project_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_history_entries");

                    b.HasIndex("HouseholdId", "AreaId")
                        .HasDatabaseName("ix_history_entries_household_id_area_id");

                    b.HasIndex("HouseholdId", "Date")
                        .HasDatabaseName("ix_history_entries_household_id_date");

                    b.HasIndex("HouseholdId", "Type")
                        .HasDatabaseName("ix_history_entries_household_id_type");

                    b.ToTable("history_entries", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.HistoryEntryPhoto", b =>
                {
                    b.Property<Guid>("HistoryEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("history_entry_id");

                    b.Property<string>("BlobKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("blob_key");

                    b.Property<string>("BlobContainer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("blob_container");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("HistoryEntryId", "BlobKey")
                        .HasName("pk_history_entry_photos");

                    b.ToTable("history_entry_photos", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.MaintenanceOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("OriginalDueDate")
                        .HasColumnType("date")
                        .HasColumnName("original_due_date");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("SnoozeReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("snooze_reason");

                    b.Property<DateTimeOffset?>("SnoozedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snoozed_at");

                    b.Property<DateOnly?>("SnoozedUntil")
                        .HasColumnType("date")
                        .HasColumnName("snoozed_until");

                    b.Property<Guid?>("SpawnedProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("spawned_project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_occurrences");

                    b.HasIndex("PlanId", "DueDate")
                        .IsUnique()
                        .HasDatabaseName("ix_maintenance_occurrences_plan_id_due_date");

                    b.HasIndex("PlanId", "Status")
                        .HasDatabaseName("ix_maintenance_occurrences_plan_id_status");

                    b.HasIndex("HouseholdId", "Status", "DueDate")
                        .HasDatabaseName("ix_maintenance_occurrences_household_id_status_due_date");

                    b.ToTable("maintenance_occurrences", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.MaintenancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AnchorDate")
                        .HasColumnType("date")
                        .HasColumnName("anchor_date");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("integer")
                        .HasColumnName("lead_time_days");

                    b.Property<int>("RecurrenceInterval")
                        .HasColumnType("integer")
                        .HasColumnName("recurrence_interval");

                    b.Property<string>("RecurrenceUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("recurrence_unit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_plans");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_maintenance_plans_household_id");

                    b.HasIndex("HouseholdId", "AreaId")
                        .HasDatabaseName("ix_maintenance_plans_household_id_area_id");

                    b.HasIndex("HouseholdId", "IsActive")
                        .HasDatabaseName("ix_maintenance_plans_household_id_is_active");

                    b.ToTable("maintenance_plans", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Medium")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TargetEndDate")
                        .HasColumnType("date")
                        .HasColumnName("target_end_date");

                    b.Property<DateOnly?>("TargetStartDate")
                        .HasColumnType("date")
                        .HasColumnName("target_start_date");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_projects_household_id");

                    b.HasIndex("HouseholdId", "AreaId")
                        .HasDatabaseName("ix_projects_household_id_area_id");

                    b.HasIndex("HouseholdId", "Priority")
                        .HasDatabaseName("ix_projects_household_id_priority");

                    b.HasIndex("HouseholdId", "Status")
                        .HasDatabaseName("ix_projects_household_id_status");

                    b.ToTable("projects", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.ProjectAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobContainer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("blob_container");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("blob_key");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_project_attachments");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_attachments_project_id");

                    b.ToTable("project_attachments", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.ProjectLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("label");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_project_links");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_links_project_id");

                    b.ToTable("project_links", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_project_tasks");

                    b.HasIndex("ProjectId", "SortOrder")
                        .HasDatabaseName("ix_project_tasks_project_id_sort_order");

                    b.ToTable("project_tasks", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.PropertyActivityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("verb");

                    b.HasKey("Id")
                        .HasName("pk_activity_events");

                    b.HasIndex("HouseholdId", "OccurredAt")
                        .HasDatabaseName("ix_activity_events_household_id_occurred_at");

                    b.HasIndex("HouseholdId", "Verb")
                        .HasDatabaseName("ix_activity_events_household_id_verb");

                    b.HasIndex("HouseholdId", "TargetType", "TargetId")
                        .HasDatabaseName("ix_activity_events_household_id_target_type_target_id");

                    b.ToTable("activity_events", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.PropertyArea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_areas");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_areas_household_id");

                    b.HasIndex("HouseholdId", "Name")
                        .HasDatabaseName("ix_areas_household_id_name");

                    b.ToTable("areas", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.PropertyIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid?>("LinkedMaintenanceOccurrenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_maintenance_occurrence_id");

                    b.Property<Guid?>("LinkedMaintenancePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_maintenance_plan_id");

                    b.Property<Guid?>("LinkedProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_project_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_issues");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_issues_household_id");

                    b.HasIndex("HouseholdId", "AreaId")
                        .HasDatabaseName("ix_issues_household_id_area_id");

                    b.HasIndex("HouseholdId", "DueDate")
                        .HasDatabaseName("ix_issues_household_id_due_date");

                    b.HasIndex("HouseholdId", "LinkedProjectId")
                        .HasDatabaseName("ix_issues_household_id_linked_project_id");

                    b.HasIndex("HouseholdId", "Severity")
                        .HasDatabaseName("ix_issues_household_id_severity");

                    b.HasIndex("HouseholdId", "Status")
                        .HasDatabaseName("ix_issues_household_id_status");

                    b.ToTable("issues", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.PropertyTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("color");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_tags_household_id");

                    b.HasIndex("HouseholdId", "Name")
                        .HasDatabaseName("ix_tags_household_id_name");

                    b.ToTable("tags", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.PropertyTagAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_tag_assignments");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_tag_assignments_household_id");

                    b.HasIndex("HouseholdId", "TargetType", "TargetId")
                        .HasDatabaseName("ix_tag_assignments_household_id_target_type_target_id");

                    b.HasIndex("HouseholdId", "TagId", "TargetType", "TargetId")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_assignments_household_id_tag_id_target_type_target_id");

                    b.ToTable("tag_assignments", "property");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.HistoryEntry", b =>
                {
                    b.OwnsOne("Hemma.Shared.Kernel.Domain.Money", "Cost", b1 =>
                        {
                            b1.Property<Guid>("HistoryEntryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("cost_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("cost_currency");

                            b1.HasKey("HistoryEntryId");

                            b1.ToTable("history_entries", "property");

                            b1.WithOwner()
                                .HasForeignKey("HistoryEntryId")
                                .HasConstraintName("fk_history_entries_history_entries_id");
                        });

                    b.Navigation("Cost");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.HistoryEntryPhoto", b =>
                {
                    b.HasOne("Hemma.Modules.Property.Domain.HistoryEntry", null)
                        .WithMany("Photos")
                        .HasForeignKey("HistoryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_history_entry_photos_history_entries_history_entry_id");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.Project", b =>
                {
                    b.OwnsOne("Hemma.Shared.Kernel.Domain.Money", "BudgetEstimate", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("budget_estimate_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("budget_estimate_currency");

                            b1.HasKey("ProjectId");

                            b1.ToTable("projects", "property");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId")
                                .HasConstraintName("fk_projects_projects_id");
                        });

                    b.Navigation("BudgetEstimate");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.ProjectAttachment", b =>
                {
                    b.HasOne("Hemma.Modules.Property.Domain.Project", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_attachments_projects_project_id");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.ProjectLink", b =>
                {
                    b.HasOne("Hemma.Modules.Property.Domain.Project", null)
                        .WithMany("Links")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_links_projects_project_id");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.ProjectTask", b =>
                {
                    b.HasOne("Hemma.Modules.Property.Domain.Project", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_tasks_projects_project_id");

                    b.OwnsOne("Hemma.Shared.Kernel.Domain.Money", "Estimate", b1 =>
                        {
                            b1.Property<Guid>("ProjectTaskId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("estimate_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("estimate_currency");

                            b1.HasKey("ProjectTaskId");

                            b1.ToTable("project_tasks", "property");

                            b1.WithOwner()
                                .HasForeignKey("ProjectTaskId")
                                .HasConstraintName("fk_project_tasks_project_tasks_id");
                        });

                    b.Navigation("Estimate");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.HistoryEntry", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Hemma.Modules.Property.Domain.Project", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Links");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
